### ISSUE TITLE
IDE Annotator

### ISSUE THREAD

**Issue by Firesphere** [CSoellinger/silverstripe-model-annotations-task#1]
Are you familiar with https://github.com/silverleague/silverstripe-ideannotator ?

**Comment by Zerogiven** [comment]
Yes but i got often got problems with the phpdocumentor/reflection-docblock required dependency so that was the biggest reason to write :)

Can't tell you now which packages made the problems along with the silverleague ideannotator, too long ago, maybe i have time to reproduce it so i could tell you where i got the dependency problems :)

It is also possible that the problems are already gone ;) 

Another thing was that i also add the use statements for short class names which comes very handy for me, cause otherwise i had to edit all files manually to add the use statements.

---

The only thing what i am still missing is how i could extend for example the Member Data Object with annotations for the IDE. But i think this only works if editing the Member file directly inside vendor, what i really do not want ^^

cheers

**Comment by Zerogiven** [comment]
But to be honest, the silverleague plugin inspired me a lot for this ;-)
